export const WORK_CHANGE = 'SET_TIME/WORK_CHANGE';
export const REST_CHANGE = 'SET_TIME/REST_CHANGE';
export const COUNTDOWN = 'SET_TIME/COUNTDOWN';
export const RESET_TIMER = 'SET_TIME/RESET_TIMER';
export const TOGGLE_START_BUTTON = 'SET_TIME/TOGGLE_START_BUTTON';